### ISSUE TITLE
SYSLIB1072

### ISSUE THREAD

**Issue by b-straub** [Elringus/JSInteropTest#1]
With lastest nightly SDK from today I still get SYSLIB1072, for Task<byte[]>. Should it be supported now?

**Comment by elringus** [comment]
Nope, it's a limitation they plan to solve at some point in future: https://github.com/dotnet/runtime/issues/81348

In [DotNetJS rewrite](https://github.com/Elringus/DotNetJS/pull/123) I'm currently serializing the content, but will probably make something more performant work out of the box. Probably generate two methods to first wait and then return the bytes w/o task.

**Comment by b-straub** [comment]
Thank you for the information!
